### ISSUE TITLE
Graphics glitch at minimum size

### ISSUE THREAD

**Issue by quite** [ultrafunk/NetInfo#1]
Hey, I like your widget a lot. Just a small thing; When I display both wifi and data, and shrink the widget to the minimum 1x2 size, there is a thin part of the text still shown. Please see the attached screenshot (nexus 5).
![screenshot_2014-11-28-08-23-09](https://cloud.githubusercontent.com/assets/488679/5224716/00c23c84-76d9-11e4-9c78-eed93fa03487.png)

**Comment by ultrafunk** [comment]
Thanks for the positive and constructive feedback. The dual widget was not designed to be used/shown at that size (1x2). However, better adaptive sizing is currently being implemented for the lock screen widgets, and it can probably be extended to include the dual home screen widget as well, which will fix the issue you have described. Unfortunately, there is no ETA for an updated version yet.

**Comment by ultrafunk** [comment]
Below is a design mock-up for using the dual home screen widget at the minimum 1x2 size showing only ON/OFF toggles for Mobile data and Wi-Fi:

![small_dual_widget](https://cloud.githubusercontent.com/assets/2698469/5239070/f312163a-78d2-11e4-9449-d3ba8e159b71.png)
