### ISSUE TITLE
no ssid with android 9

### ISSUE THREAD

**Issue by paulle** [ultrafunk/NetInfo#11]
The net info widget doesn't show ssid since my device was updated to android 9.0.
It says unknown ssid.
Other apps are showing the ssid correct on my phone (sony xz2).

**Comment by ultrafunk** [comment]
The NetInfo widget will not be developed any further by Ultrafunk so no new features will be implemented and no bugs will be fixed, but thanks for the feedback. NetInfo is Open Source so anyone can fork it.
