### ISSUE TITLE
Not showing in widget list

### ISSUE THREAD

**Issue by JonnyTech** [ultrafunk/NetInfo#4]
I have just installed netinfo from fdroid but the widgets are not showing in the widget list so I cannot use them. Running Android 5.1.1 - latest CyanogenMod.

**Comment by ultrafunk** [comment]
It should show up as a single widget named "NetInfo" (see the attached image below):

![netinfo_widget](https://cloud.githubusercontent.com/assets/2698469/9718777/240d552c-557f-11e5-9eeb-3c77af5b9a79.png)

Adding a widget to the widget list is done automatically by Android using the APKs AndroidManifest.xml file, so I don't think this is an issue with my code or implementation as far as I can tell. Unfortunately I don't have access to any device running any version of CyanogenMod, so I'm unable to debug / troubleshoot this issue any further.
