### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not Present, as of: 1.8.1.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [ultrafunk/NetInfo#8]

**Comment by ultrafunk** [comment]
NetInfo has been added to F-Droid without our knowledge and consent. Google Play is the only supported distribution channel and it has a changelog:

https://play.google.com/store/apps/details?id=com.ultrafunk.network_info

**Comment by locutis-of-borg-1999** [comment]
Sad.  Well then it doesn't seem to be truly FOSS (Free & Open Source Software).  

Google has "remote kill switch", and other proprietary "remedies".   Via that, Google could uninstall it, withOUT my consent.  But I've done so, as you only want Google to have control.

**Comment by ultrafunk** [comment]
Your last comment was accidentally deleted and we are sorry about that (there is no way to undelete issue comments), it is quoted fully below:

> Sad.  Well then it doesn't seem to be truly FOSS (Free & Open Source Software).  
> 
> Google has "remote kill switch", and other proprietary "remedies".   Via that, Google could uninstall it, withOUT my consent.  But I've done so, as you only want Google to have control.  

If you want a changelog link within the F-Droid App: Please feel free to contribute the relevant code to this project or make an F-Droid specific fork with any changes you think are needed.

**Comment by locutis-of-borg-1999** [comment]
https://f-droid.org/manual/html_node/Changelog.html#Changelog
